---
site_name: YVtils Documentation
site_url: https://docs.yvtls.net

theme: 
  logo: assets/logo_transparent.webp
  favicon: assets/logo_transparent.webp
  name: material
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      github: GitHub
      analytics: Analytics
    actions:
      accept: Accept
      reject: Reject
      manage: Manage

  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
      provider: google
      property: G-9SWTVZRJK8

copyright: >
  Copyright &copy; 2016 - 2024 Martin Donath –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - mkdocs-video
  - search
markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


nav:
  - Home: index.md
  - SMP:
    - config.yml: smp/config.yml.md
    - Admin:
      - mutedPlayers.yml: smp/admin/mutedPlayers.yml.md
    - Discord:
      - config.yml: smp/discord/config.yml.md
      - save.yml: smp/discord/save.yml.md
    - Fusions:
      - fusionName.yml: smp/fusions/fusionName.yml.md
    - Language:
      - language.yml: smp/language/language.yml.md
    - MultiMine:
      - config.yml: smp/multiMine/config.yml.md
    - Server:
      - config.yml: smp/server/config.yml.md
    - Status:
      - config.yml: smp/status/config.yml.md
      - save.yml: smp/status/save.yml.md
    - Waypoints:
      - config.yml: smp/waypoints/config.yml.md
      - save.yml: smp/waypoints/save.yml.md
  - Color Codes: colorcode.md