---
site_name: YVtils Documentation

theme: 
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - mkdocs-video
markdown_extensions:
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


nav:
  - Home: index.md
  - SMP:
    - config.yml: smp/config.yml.md
    - Admin:
      - mutedPlayers.yml: smp/admin/mutedPlayers.yml.md
    - Discord:
      - config.yml: smp/discord/config.yml.md
      - save.yml: smp/discord/save.yml.md
    - Fusions:
      - fusionName.yml: smp/fusions/fusionName.yml.md
    - Language:
      - language.yml: smp/language/language.yml.md
    - MultiMine:
      - config.yml: smp/multiMine/config.yml.md
    - Server:
      - config.yml: smp/server/config.yml.md
    - Status:
      - config.yml: smp/status/config.yml.md
      - save.yml: smp/status/save.yml.md
    - Waypoints:
      - config.yml: smp/waypoints/config.yml.md
      - save.yml: smp/waypoints/save.yml.md
  - Color Codes: colorcode.md